# Generated by Django 3.2.5 on 2021-09-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='slug',
        ),
    ]
