# Generated by Django 3.2.5 on 2021-09-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_user_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='user',
        ),
    ]
